# Test Runner Script (PowerShell)
# Run all tests in the harness

Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "AI Agent Harness - Test Runner" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

# Create results directory with timestamp
$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$resultsDir = "results\run_$timestamp"
New-Item -ItemType Directory -Path $resultsDir -Force | Out-Null

Write-Host "Results will be saved to: $resultsDir" -ForegroundColor Yellow
Write-Host ""

# Run unit tests
Write-Host "Running Unit Tests..." -ForegroundColor Green
Get-ChildItem "tests\unit\*.md" | ForEach-Object {
  Write-Host "  - $($_.Name)"
  $outputFile = "$resultsDir\unit_$($_.BaseName).txt"
  $content = Get-Content $_.FullName -Raw
  opencode run "$content" > $outputFile 2>&1
}
Write-Host ""

# Run integration tests
Write-Host "Running Integration Tests..." -ForegroundColor Green
Get-ChildItem "tests\integration\*.md" | ForEach-Object {
  Write-Host "  - $($_.Name)"
  $outputFile = "$resultsDir\integration_$($_.BaseName).txt"
  $content = Get-Content $_.FullName -Raw
  opencode run "$content" > $outputFile 2>&1
}
Write-Host ""

# Run benchmarks
Write-Host "Running Benchmarks..." -ForegroundColor Green
Get-ChildItem "tests\benchmarks\*.md" | ForEach-Object {
  Write-Host "  - $($_.Name)"
  $outputFile = "$resultsDir\benchmark_$($_.BaseName).txt"
  $content = Get-Content $_.FullName -Raw
  opencode run "$content" > $outputFile 2>&1
}
Write-Host ""

# Generate report
Write-Host "Generating Report..." -ForegroundColor Yellow
$unitCount = (Get-ChildItem "$resultsDir\unit_*.txt" -ErrorAction SilentlyContinue).Count
$integrationCount = (Get-ChildItem "$resultsDir\integration_*.txt" -ErrorAction SilentlyContinue).Count
$benchmarkCount = (Get-ChildItem "$resultsDir\benchmark_*.txt" -ErrorAction SilentlyContinue).Count

$report = @"
# Test Run Report

**Date:** $(Get-Date)
**Total Tests:** $($unitCount + $integrationCount + $benchmarkCount)

## Results

### Unit Tests
$unitCount tests executed

### Integration Tests
$integrationCount tests executed

### Benchmarks
$benchmarkCount benchmarks executed

## Output Files

$(Get-ChildItem "$resultsDir\*.txt" -ErrorAction SilentlyContinue | ForEach-Object { "- $($_.Name)" })

---
Generated by Agent Harness
"@

$report | Set-Content "$resultsDir\report.md"

Write-Host ""
Write-Host "==========================================" -ForegroundColor Green
Write-Host "Test run complete!" -ForegroundColor Green
Write-Host "Results: $resultsDir\report.md" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green
