#!/bin/bash
# Run all tests in the harness

echo "=========================================="
echo "AI Agent Harness - Test Runner"
echo "=========================================="
echo ""

# Create results directory with timestamp
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
RESULTS_DIR="results/run_${TIMESTAMP}"
mkdir -p "$RESULTS_DIR"

echo "Results will be saved to: $RESULTS_DIR"
echo ""

# Run unit tests
echo "Running Unit Tests..."
for test in tests/unit/*.md; do
  if [ -f "$test" ]; then
    echo "  - $(basename "$test")"
    opencode run "$(cat "$test")" > "$RESULTS_DIR/unit_$(basename "$test" .md).txt" 2>&1
  fi
done
echo ""

# Run integration tests
echo "Running Integration Tests..."
for test in tests/integration/*.md; do
  if [ -f "$test" ]; then
    echo "  - $(basename "$test")"
    opencode run "$(cat "$test")" > "$RESULTS_DIR/integration_$(basename "$test" .md).txt" 2>&1
  fi
done
echo ""

# Run benchmarks
echo "Running Benchmarks..."
for test in tests/benchmarks/*.md; do
  if [ -f "$test" ]; then
    echo "  - $(basename "$test")"
    opencode run "$(cat "$test")" > "$RESULTS_DIR/benchmark_$(basename "$test" .md).txt" 2>&1
  fi
done
echo ""

# Generate report
echo "Generating Report..."
cat > "$RESULTS_DIR/report.md" << EOF
# Test Run Report

**Date:** $(date)
**Total Tests:** $(ls tests/*/*.md 2>/dev/null | wc -l)

## Results

### Unit Tests
$(ls -1 "$RESULTS_DIR"/unit_*.txt 2>/dev/null | wc -l) tests executed

### Integration Tests
$(ls -1 "$RESULTS_DIR"/integration_*.txt 2>/dev/null | wc -l) tests executed

### Benchmarks
$(ls -1 "$RESULTS_DIR"/benchmark_*.txt 2>/dev/null | wc -l) benchmarks executed

## Output Files

$(ls -1 "$RESULTS_DIR"/*.txt 2>/dev/null | sed 's/^/- /')

---
Generated by Agent Harness
EOF

echo ""
echo "=========================================="
echo "Test run complete!"
echo "Results: $RESULTS_DIR/report.md"
echo "=========================================="
